### ISSUE TITLE
"STrace" service not initiating.

### ISSUE THREAD

**Issue by EgeBalci** [mandiant/STrace#20]
Hi,

I compiled the entire project on VS Community 2022 without any errors. I ran the install script as admin, and it was completed successfully. But after rebooting with DSE disabled, the STrace service did not start.

![image](https://github.com/mandiant/STrace/assets/17179401/05a0c6c3-d255-4ae4-a6e6-f4011a7136d1)

As described in readme, I tried to start it manually but I'm having the following error.

![image](https://github.com/mandiant/STrace/assets/17179401/2e619d51-1544-4a45-9734-fb5984f5e051)

I'm using a Windows 10 VM (Flare VM) on VirtualBox with nested virtualization enabled. Is there anyone else having this issue?

**Comment by EgeBalci** [comment]
After repeating the entire installation process with the pre-built release binaries, it somehow worked.

**Comment by stevemk14ebr** [comment]
The windows system is a bit finicky, I usually have to install, then reboot twice
