### ISSUE TITLE
.NET PDBs

### ISSUE THREAD

**Issue by Ana06** [mandiant/STrace#32]
At the moment `PDBReSym.exe cachesyms` iterates through `C:\Windows\System32` downloading all PDBs to `C:\symbols`. 

Proposing to in addition download `C:\Windows\Microsoft.NET` which is useful for .NET debugging (when dnspy doesn't work). Or is there a way to do this already?

**Comment by stevemk14ebr** [comment]
Try invoking PDBReSym for a second time with the sysdir command line option set to the .net directory. This is a sub flag of the cachesysms command line option

**Comment by Ana06** [comment]
`PDBReSym.exe cachesyms --sysdir "C:\Windows\Microsoft.NET"` works, thanks @stevemk14ebr!
