### ISSUE TITLE
DeviceIoControl for LOADDLL failed, error 31

### ISSUE THREAD

**Issue by unknown-re** [mandiant/STrace#4]
i keep having this error on the CLI .

_[+] Opening driver
[+] Driver Opened Successfully
Input command: load, unload, exit
LOAD
Input command: load, unload, exit
LOAD
Input command: load, unload, exit
load
[+] Asking for plugin
Input command: load, unload, exit
load_

**Comment by stevemk14ebr** [comment]
It's case sensitive

**Comment by unknown-re** [comment]
i know once it's loaded where am i supposed to see the output ? dbgview doesn't show up a thing

**Comment by stevemk14ebr** [comment]
Depends on the plugin. All my examples create a log file on the root C drive.

**Comment by unknown-re** [comment]
i don't see any syscalls on the strace.log

only

22:44:37.793  INF #2   8888  Log has been initialized.
22:44:37.793  INF #2   8888  Starting DLL unload
22:44:37.793  ERR #2   8888  [!] No plugin is loaded, unload failed
22:44:41.270  INF #4   8888  Starting DLL unload
22:44:41.270  ERR #4   8888  [!] No plugin is loaded, unload failed
22:48:50.290  INF #6   8888  Starting DLL unload
22:48:50.290  ERR #6   8888  [!] No plugin is loaded, unload failed
22:48:55.277  INF #6   8888  Starting DLL load
22:48:55.277  INF #6   8888  [+] Executing DLLMain
22:48:55.277  INF #6   8888  [+] DLL Load Done
22:48:55.277  INF #6   8888  [+] Dll Mapped at FFFFE684D8791000
22:48:55.277  INF #6   8888  Plugin Initializing...
22:48:55.277  INF #6   8888  Plugin Initialized
22:50:13.980  INF #8   8888  Starting DLL load
22:50:13.980  ERR #8   8888  [!] Only one plugin may be loaded at a time, load failed

**Comment by stevemk14ebr** [comment]
https://github.com/mandiant/STrace/blob/main/C/STrace/driver.cpp#L113

**Comment by unknown-re** [comment]
i'm more likely interessed into this feature
https://github.com/mandiant/STrace/blob/main/C/LogSyscallsPlugin/dllmain.cpp#L1904

**Comment by unknown-re** [comment]
Holly shieet that 's fast as fuck , very good job man.
