### ISSUE TITLE
Question about pdb-addr2line and end_rva

### ISSUE THREAD

**Issue by mstange** [mandiant/STrace#7]
Hi, I made pdb-addr2line and saw the following comment in your code:

https://github.com/mandiant/STrace/blame/27e57cd6f990b824063a1c27a7612e3226af5340/Rust/PDBReSym/src/main.rs#L307

```rust
// if a line has no end rva, the start of the next block defines it's end. Lots of symbols are like this.
```

How up-to-date is that comment? Do you still get lots of symbols with a missing end_rva? I tried to mostly fix this issue in pdb-addr2line 0.7.2, with these commits:
https://github.com/mstange/pdb-addr2line/commit/8787f38644c7b0b22f1ce192c08f45ff8676bd9f
https://github.com/mstange/pdb-addr2line/commit/0bdb486bf498b027cbac977de733d102211faa5f

So I'd expect basically all symbols to have an end_rva now. If this is true, it might simplify your code.

**Comment by stevemk14ebr** [comment]
I haven't checked in a while, I originally wrote this over a year ago. I'll do some testing sometime!
